"""Note chunks: one row per note, `content_tsv` generated by Postgres,
`embedding` nullable until `switchboard_core.prose.embed_pending` fills it.

Creates the `prose` schema, empty until this same migration fills it with the
one table it holds - unlike `source`/`knowledge`, there is no earlier
migration that already created it. See the `NoteChunk` model's docstring for
why `embedding` is nullable and why there is no ANN index on it.

Revision ID: 0004
Revises: 0003
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

import switchboard_core.db.base

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("CREATE SCHEMA IF NOT EXISTS prose")

    op.create_table(
        "note_chunks",
        sa.Column("note_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("content", sa.String(), nullable=False),
        sa.Column(
            "content_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('english', content)", persisted=True),
            nullable=False,
        ),
        sa.Column("embedding", switchboard_core.db.base.Vector(1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["source.jobs.id"], name=op.f("fk_note_chunks_job_id_jobs")
        ),
        sa.ForeignKeyConstraint(
            ["note_id"], ["source.notes.id"], name=op.f("fk_note_chunks_note_id_notes")
        ),
        sa.PrimaryKeyConstraint("note_id", name=op.f("pk_note_chunks")),
        schema="prose",
    )
    op.create_index(
        "ix_note_chunks_content_tsv",
        "note_chunks",
        ["content_tsv"],
        unique=False,
        schema="prose",
        postgresql_using="gin",
    )
    op.create_index(
        "ix_note_chunks_job_id", "note_chunks", ["job_id"], unique=False, schema="prose"
    )


def downgrade() -> None:
    op.drop_index("ix_note_chunks_job_id", table_name="note_chunks", schema="prose")
    op.drop_index(
        "ix_note_chunks_content_tsv",
        table_name="note_chunks",
        schema="prose",
        postgresql_using="gin",
    )
    op.drop_table("note_chunks", schema="prose")
    op.execute("DROP SCHEMA IF EXISTS prose")
